name: PayPay Node SDK Upload CI Results
on:
  workflow_run:
    workflows: ["Paypay Node SDK CI"]
    types: ["completed"]
jobs:
  upload-codeclimate:
    runs-on: ubuntu-latest
    steps:
    - name: codeclimate before-build
      env: 
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID}}
      run: |
           curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
           chmod +x ./cc-test-reporter
           ./cc-test-reporter before-build

    - name: Download coverage from CI run
      uses: actions/download-artifact@v2
      with:
        name: coverage-lcov-14.x.info
        path: artifacts/

    - name: Show structure
      run: ls -R

    - name: codeclimate after-build
      env: 
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID}}
      run: ./cc-test-reporter after-build artifacts/lcov.info --exit-code 0
