name: Paypay Node SDK CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 12.x, 10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: coveralls
      run: yarn coveralls
      continue-on-error: true

    - name: Upload coverage GitHub artifact
      uses: actions/upload-artifact@v2
      with:
        # Consumed by the `build-ci-target.yml` `upload-codeclimate` job.
        name: lcov-${{ matrix.node-version }}
        path: ./coverage/

    - name: Upload coverall reports
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Upload to CoPilot
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
